/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.duke.maki.bosh.form;

import com.duke.maki.bosh.controller.Controller;
import java.awt.event.ItemEvent;
import java.util.List;

/**
 *
 * @author Lazar Milosavljević
 */
public class WindowApp extends javax.swing.JFrame {

    private Controller controller;
    /**
     * Creates new form WindowApp
     */
    public WindowApp(Controller controller) {
        initComponents();
        this.controller=controller;
        
        this.inputDir1.setText(controller.getInputDir());
        this.outputDir.setText(controller.getOutputDir());
        List<String> inputNames=controller.getInputFiles();
        inputNames.forEach((inputName) -> {
            this.inputFileNames.addItem(inputName);
        });
        this.setButtonEnable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        outputDir = new javax.swing.JTextField();
        inputFileNames = new javax.swing.JComboBox<>();
        inputDir1 = new javax.swing.JTextField();
        outputName = new javax.swing.JTextField();
        fileFormat = new javax.swing.JTextField();
        convertButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        outputDir.setEditable(false);

        inputFileNames.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                inputFileNamesItemStateChanged(evt);
            }
        });

        inputDir1.setEditable(false);

        outputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                outputNameActionPerformed(evt);
            }
        });
        outputName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                outputNameKeyPressed(evt);
            }
        });

        fileFormat.setEditable(false);

        convertButton.setText("Convert");
        convertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                convertButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(convertButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inputFileNames, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(fileFormat, javax.swing.GroupLayout.DEFAULT_SIZE, 393, Short.MAX_VALUE)
                            .addComponent(outputDir, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(outputName, javax.swing.GroupLayout.Alignment.LEADING))))
                .addGap(98, 98, 98))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(inputDir1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(529, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(outputDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputFileNames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(outputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(fileFormat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(convertButton, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(23, 23, 23)
                    .addComponent(inputDir1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(387, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inputFileNamesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_inputFileNamesItemStateChanged
        
        if (evt.getStateChange() == ItemEvent.SELECTED){
            String item=(String)evt.getItem();
            String extension= this.controller.getExtention(item);
            this.fileFormat.setText(extension);
        }
    }//GEN-LAST:event_inputFileNamesItemStateChanged

    private void convertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_convertButtonActionPerformed
        this.controller.convert((String)this.inputFileNames.getSelectedItem(),this.outputName.getText(),this.fileFormat.getText());
    }//GEN-LAST:event_convertButtonActionPerformed

    private void outputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_outputNameActionPerformed
        this.setButtonEnable();
    }//GEN-LAST:event_outputNameActionPerformed

    private void outputNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_outputNameKeyPressed
         this.setButtonEnable();
    }//GEN-LAST:event_outputNameKeyPressed
    public void setButtonEnable(){
        boolean b= !this.inputFileNames.getSelectedItem().equals("") && !this.outputName.getText().equals("") && !this.fileFormat.getText().equals("");
        
        this.convertButton.setEnabled(b);
        this.repaint();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton convertButton;
    private javax.swing.JTextField fileFormat;
    private javax.swing.JTextField inputDir1;
    private javax.swing.JComboBox<String> inputFileNames;
    private javax.swing.JTextField outputDir;
    private javax.swing.JTextField outputName;
    // End of variables declaration//GEN-END:variables
}
